version: "3.8"
services:
  etl:
    build:
      context: .
    volumes:
      - ./etl:/etl
  db:
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mysql:5.6
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql
    ports:
      - 3306:3306
